# Generated by Django 4.2.4 on 2023-08-14 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alies', '0034_alter_receipt_date_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 20, 14, 54, 696066)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='8095058186', max_length=10, unique=True),
        ),
    ]
