# Generated by Django 4.2.4 on 2023-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('items', models.TextField()),
                ('ref_num', models.CharField(blank=True, default='2850302476', editable=False, max_length=10, unique=True)),
            ],
        ),
    ]
