# Generated by Django 4.2.4 on 2023-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(blank=True, default='7090977222', editable=False, max_length=10, unique=True),
        ),
    ]
