# Generated by Django 4.2.4 on 2023-08-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0018_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='5400820772', editable=False, max_length=10, unique=True),
        ),
    ]
