# Generated by Django 4.2.4 on 2023-08-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0019_alter_receipt_ref_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('itemcount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ref_num',
            field=models.CharField(default='4824489768', editable=False, max_length=10, unique=True),
        ),
    ]
